import esbuild from "esbuild";
import sveltePlugin from "esbuild-svelte";
import sveltePreprocess from "svelte-preprocess";


const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

esbuild
    .build({
        banner: {
            js: banner
        },
        entryPoints: ["src/main.ts", "src/styles.css"],
        bundle: true,
        external: ["obsidian"],
        format: "cjs",
        watch: true,
        target: "es2020",
        logLevel: "info",
        sourcemap: "inline",
        treeShaking: true,
        plugins: [
            sveltePlugin({
                compilerOptions: { css: true },
                preprocess: sveltePreprocess()
            })
        ],
        outdir: "./"
    })
    .catch(() => process.exit(1));